logging:
  level:
    root: INFO
crawler:
  seeds: https://www.librariilealexandria.ro/, https://www.libris.ro/, https://carturesti.ro/, https://www.domo.ro/, https://www.bookdepository.com/
  page:
    limit: 2000
  user.agent: Chillbot/1.0
filesystem:
  target: file:///home/mircea/crawler-files