logging:
  level:
    root: INFO
crawler:
  seeds: https://www.librariilealexandria.ro/, https://www.libris.ro/
  page:
    limit: 600
  user.agent: Chillbot/1.0
filesystem:
  documents:
    path: file:///C:/Users/mircea.dobreanu/crawler_files/documents
  back:
    links:
      path: file:///C:/Users/mircea.dobreanu/crawler_files/back_links
  reverse:
    lookup:
      path: file:///C:/Users/mircea.dobreanu/crawler_files/reverse_lookup